### User Register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
     "firstName":"Shiva",
     "lastName":"kumar",
     "email":"shiav@gmail.com",
     "password":"shiva",
     "profileImageUrl":"http://example/dp.png"
}

### user login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
     "email":"shiavreddy@gmail.com",
     "password":"shivareddy"
}
### Author Register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
     "firstName":"Sk",
     "lastName":"Reddy",
     "email":"skreddy@gmail.com",
     "password":"shiva",
     "profileImageUrl":"http://example/dp1.png"
}

### create artical
POST http://localhost:4000/author-api/article
Content-Type: application/json

{
     "author":"698998eac4832acc5014217c",
     "title":"Python",
     "category":"programming",
     "content":"thi is Python article"
}

### read artical
GET http://localhost:4000/author-api/articles/6989675802eea340b551ddad


### update the artical
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
     "author":"6989675802eea340b551ddad",
     "articleId":"69897a58d5fe72ec8d2ec095",
     "title":"Java",
     "category":"programming",
     "content":"updated content"
}
### soft delete the article

PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
     "author":"6989675802eea340b551ddad",
     "articleId":"69897a58d5fe72ec8d2ec095"
}

###logout
GET http://localhost:4000/common-api/logout


### get article by user
GET http://localhost:4000/user-api/article

### add comment to article

PUT http://localhost:4000/user-api/articleComment 
Content-Type: application/json

{
     "user":"69896605cf8432c768c1a9b7",
     "articleId":"69899904c4832acc5014217f",
     "comment":"good"
}


###Test Request
GET http://localhost:4000/test

###block  by admin
PUT http://localhost:4000/admin-api/blockuser/69896605cf8432c768c1a9b7

###block  by admin
PUT http://localhost:4000/admin-api/unblockuser/69896605cf8432c768c1a9b7

### updatepassword
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
     "email":"shiavreddy@gmail.com",
     "currentPassword":"12345",
     "newPassword":"shivareddy"
}